name: CI-Dev

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-lint-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v3

      - name: Install docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.17.2'
        
      # - uses: satackey/action-docker-layer-caching@v0.0.11
      #   continue-on-error: true

      - name: Launch app 
        run: |
          make up
      
      - name: Wait until the containers are finished launching
        run: |
          sleep 5

      - name: Run Linter 
        run: |
          make linter_check

      - name: Run Coverage 
        run: |
          make coverage

      - name: Stop app 
        if: always()
        run: |
          make down
